// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi.Data;

namespace WebApi.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    partial class ApiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5");

            modelBuilder.Entity("WebApi.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemsIds")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Orders","order");

                    b.HasData(
                        new
                        {
                            Id = new Guid("05284a3a-ce7b-48ed-b2f8-1db52f4e7db3"),
                            Currency = "ARS",
                            ItemsIds = "1,2,3"
                        },
                        new
                        {
                            Id = new Guid("fde167d5-8721-41d0-9503-65bd8f1af67b"),
                            Currency = "EUR",
                            ItemsIds = "1,2,3"
                        },
                        new
                        {
                            Id = new Guid("9e99cf8b-ba6f-48ad-87ad-3e2127ffff21"),
                            Currency = "USD",
                            ItemsIds = "1,2,3"
                        },
                        new
                        {
                            Id = new Guid("4e7ac029-8816-426c-b689-447d213a7086"),
                            Currency = "BRL",
                            ItemsIds = "1,2,3"
                        },
                        new
                        {
                            Id = new Guid("7f55bcef-c616-4e61-b15c-d867021b8699"),
                            Currency = "???",
                            ItemsIds = "1,2,3"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
